CREATE TABLE IF NOT EXISTS t_agent_task (
    task_id               CHAR(36)      NOT NULL PRIMARY KEY,
    session_id            BIGINT,
    host_id               BIGINT,
    request_hash          CHAR(64)      NOT NULL,
    task_text             TEXT          NOT NULL,
    status                VARCHAR(32)   NOT NULL,
    phase                 VARCHAR(32)   NOT NULL,
    cancel_requested      TINYINT       NOT NULL DEFAULT 0,
    deadline_at           TIMESTAMP,
    model_calls           INT           NOT NULL DEFAULT 0,
    tool_calls            INT           NOT NULL DEFAULT 0,
    consecutive_failures  INT           NOT NULL DEFAULT 0,
    next_step_sequence    BIGINT        NOT NULL DEFAULT 1,
    next_event_sequence   BIGINT        NOT NULL DEFAULT 1,
    final_summary         CLOB,
    error_code            VARCHAR(64),
    error_message         CLOB,
    version               BIGINT        NOT NULL DEFAULT 0,
    started_at            TIMESTAMP,
    finished_at           TIMESTAMP,
    created_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS t_agent_step (
    step_id                CHAR(36)      NOT NULL PRIMARY KEY,
    task_id                CHAR(36)      NOT NULL,
    sequence_no            INT           NOT NULL,
    tool_call_id           VARCHAR(128)  NOT NULL,
    phase                  VARCHAR(32)   NOT NULL,
    step_type              VARCHAR(32)   NOT NULL,
    status                 VARCHAR(32)   NOT NULL,
    tool_name              VARCHAR(128),
    arguments_json         CLOB,
    action_digest          CHAR(64)      NOT NULL,
    risk_level             VARCHAR(16),
    policy_version         VARCHAR(32),
    matched_rules          CLOB,
    pre_snapshot           CLOB,
    result_summary         CLOB,
    exit_code              INT,
    timed_out              TINYINT       NOT NULL DEFAULT 0,
    truncated              TINYINT       NOT NULL DEFAULT 0,
    verification_plan      CLOB,
    verification_result    CLOB,
    rollback_suggestion    CLOB,
    version                BIGINT        NOT NULL DEFAULT 0,
    started_at             TIMESTAMP,
    finished_at            TIMESTAMP,
    created_at             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_test_step_action UNIQUE (task_id, tool_call_id, action_digest),
    CONSTRAINT uk_test_step_sequence UNIQUE (task_id, sequence_no)
);

CREATE TABLE IF NOT EXISTS t_agent_approval (
    approval_id    CHAR(36)      NOT NULL PRIMARY KEY,
    task_id        CHAR(36)      NOT NULL,
    step_id        CHAR(36)      NOT NULL,
    tool_call_id   VARCHAR(128)  NOT NULL,
    action_digest  CHAR(64)      NOT NULL,
    status         VARCHAR(16)   NOT NULL,
    risk_level     VARCHAR(16),
    reason         CLOB,
    matched_rules  CLOB,
    expires_at     TIMESTAMP     NOT NULL,
    decided_at     TIMESTAMP,
    version        BIGINT        NOT NULL DEFAULT 0,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_test_approval_action UNIQUE (task_id, tool_call_id, action_digest)
);

CREATE TABLE IF NOT EXISTS t_agent_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id      CHAR(36)     NOT NULL,
    sequence_no  BIGINT       NOT NULL,
    event_type   VARCHAR(64)  NOT NULL,
    payload_json CLOB         NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_test_event_sequence UNIQUE (task_id, sequence_no)
);

CREATE TABLE IF NOT EXISTS t_idempotency_record (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope            VARCHAR(32)   NOT NULL,
    idempotency_key  VARCHAR(128)  NOT NULL,
    request_hash     CHAR(64)      NOT NULL,
    resource_id      VARCHAR(64),
    response_status  INT,
    response_json    CLOB,
    expires_at       TIMESTAMP     NOT NULL,
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_test_idempotency UNIQUE (scope, idempotency_key)
);
